### ISSUE TITLE
react rekommenderar en polyfill för att undvika XSS i gamla browsers

### ISSUE THREAD

**Issue by alexanderkjall** [revinfrastruct/megafon#7]
Det här är en väldigt teoretisk vektor, men om något skulle gå fel i inputen till tickern så skulle kanske någon kunna injecta json som genererar en XSS i react.

React rekommenderar att man använder en polyfill för att minska den risken i gamla browsers här:
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#notable-enhancements

Ni som är bättre på javascript får värdera om det här är något reellt.

Men det vore bra att ha en plan för vad som händer om någon lyckas injecta events in i tickern, så att inte alla klienterna blir vuln.

**Comment by alfreddatakillen** [comment]
Babel är en del av kopilering/transpileringen/whatever, så om jag tolkar texten rätt, så löser Babel det här åt oss redan. Men det är en gissning utifrån texten, så vi bör kolla upp det genom att titta på den färdiga koden också.

(Vidare så vore det kanske en poäng att validera input från JSON-blobben hursomhelst...)

**Comment by alexanderkjall** [comment]
Jag såg inte babel-polyfill i listan på dependencies, men det kanske är något annat som dependar på den så att den kommer med ändå?

**Comment by alfreddatakillen** [comment]
Hmm, jadu, inte lätt att se på rak arm. Bland paketen som landar i `node_modules` så finns den här polyfillen för Symbol: [es6-symbol](https://github.com/medikoo/es6-symbol) och en rad olika moduler som dependar på den, men om den används där vår JSON-data landar har jag inte luskat ut (än). :)
